### ISSUE TITLE
Querying metrics is slower in v0.2.4

### ISSUE THREAD

**Issue by devasmith** [tynany/frr_exporter#11] opened 2020-04-22 06:20 UTC
Hi. We are seeing much slower queries than before in the latest version, see comparison below.

version v0.2.4:
`~# time curl localhost:9342/metrics > /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 10850  100 10850    0     0  27473      0 --:--:-- --:--:-- --:--:-- 27538

real    0m0.407s
user    0m0.004s
sys     0m0.008s
`

version v0.1.2:
`~# time curl localhost:9342/metrics > /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 21155  100 21155    0     0   132k      0 --:--:-- --:--:-- --:--:--  133k

real    0m0.170s
user    0m0.008s
sys     0m0.004s
`

**Comment by tynany** [comment] 2020-04-25 04:21
This is caused by the `frr_bgp_peer_prefixes_advertised_count_total` metric which was added as part of https://github.com/tynany/frr_exporter/issues/10. Unfortunately, FRR does not expose a summary of advertised prefixes for all peers-- instead, you need to query FRR for each peer. From my testing, each peer adds ~50ms of latency while frr_exporter runs `show bgp ipv4 unicast neighbors $neighbor advertised-routes json` for each peer. 

Is this added delay an issue? The default timeout on a Prometheus scraper is 30 seconds when scraping exporter endpoints. You'd need ~600 peers for a scrape to take 30 seconds. I'll take a look to see if there are improvements that can be made, but please keep in mind there is always going to be added latency until FRR exposes a summary of advertised routes.

**Comment by r0bj** [comment] 2020-05-19 20:38
In our case, using 0.2.2 metric query takes ~2s and after upgrade to 0.2.4 we cannot get any metrics at all (I was waiting for 5 minutes http result).

**Comment by tynany** [comment] 2020-05-21 11:41
I have released https://github.com/tynany/frr_exporter/releases/tag/v0.2.5 which should address some of these issues:

@devasmith the vtysh commands used to collect advertised prefix counts are now parallelised, but from my testing, it seems vtysh/FRR still executes these in serial. Can you please try the new version and let me know if you are still experiencing slow queries to frr_exporter? Another option I want to explore is leveraging vtysh's supports of multiple commands (i.e. `vtysh -c 'command1' -c 'command2'). The only downfall is the unstructured nature of the output (i.e. multiple JSON outputs merged as a single text output).

@r0bj I wasn't able to replicate your issue -- can you please provide more information? In version 0.2.5, `frr_bgp_peer_prefixes_advertised_count_total` is disabled by default and needs to be enabled via the `--collector.bgp.advertised-prefixes` flag. If you are experiencing scrape times > 5 minutes, I suspect `vtysh` is timing out, so I've implemented a configurable `vtysh` timeout via the `--frr.vtysh.timeout` flag. The default is 20 seconds. Can you please let me know if this satisfies your current issue?

**Comment by r0bj** [comment] 2020-05-21 23:50
@tynany indeed, it was `vtysh` timeout. 0.2.5 with disabled `frr_bgp_peer_prefixes_advertised_count_total` works fine for me. Thanks!

**Closed** 2020-08-05 21:51 UTC
